/*
 * Matter replacement sample PoC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ExclusionsDelete - Delete exclusions
func ExclusionsDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ExclusionsPost - Exempt a policy for a given client
func ExclusionsPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
