/*
 * Matter replacement sample PoC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ExclusionsPostRequest struct {

	ClientId string `json:"client_id,omitempty"`

	Policy string `json:"policy,omitempty"`
}
