/*
 * Matter replacement sample PoC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Policy struct {

	Name string `json:"name,omitempty"`

	Version string `json:"version,omitempty"`

	Location string `json:"location,omitempty"`
}
