/*
 * Matter replacement sample PoC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"math/rand"
	"net/http"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// ConfigsDelete - Delete configurations
func (s *DefaultApiService) ConfigsDelete(ctx context.Context, policy string, clientId string, policyVersion string) (ImplResponse, error) {
	// TODO - update ConfigsDelete with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Metadata{}) or use other options such as http.Ok ...
	//return Response(200, Metadata{}), nil

	//TODO: Uncomment the next line to return response Response(202, Metadata{}) or use other options such as http.Ok ...
	//return Response(202, Metadata{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConfigsDelete method not implemented")
}

// ConfigsGet - Get configurations
func (s *DefaultApiService) ConfigsGet(ctx context.Context, clientId string, policy string, policyVersion string) (ImplResponse, error) {
	// TODO - update ConfigsGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ConfigsGet200Response{}) or use other options such as http.Ok ...
	//return Response(200, ConfigsGet200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ConfigsGet method not implemented")
}

// ExclusionsDelete - Delete exclusions
func (s *DefaultApiService) ExclusionsDelete(ctx context.Context, policy string, clientId string) (ImplResponse, error) {
	// TODO - update ExclusionsDelete with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Metadata{}) or use other options such as http.Ok ...
	//return Response(200, Metadata{}), nil

	//TODO: Uncomment the next line to return response Response(202, Metadata{}) or use other options such as http.Ok ...
	//return Response(202, Metadata{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ExclusionsDelete method not implemented")
}

// ExclusionsPost - Get exclusions
func (s *DefaultApiService) ExclusionsPost(ctx context.Context, exclusionsPostRequest ExclusionsPostRequest) (ImplResponse, error) {
	// TODO - update ExclusionsPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Metadata{}) or use other options such as http.Ok ...
	//return Response(200, Metadata{}), nil

	//TODO: Uncomment the next line to return response Response(202, Metadata{}) or use other options such as http.Ok ...
	//return Response(202, Metadata{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ExclusionsPost method not implemented")
}

// InfoGet - Get info
func (s *DefaultApiService) InfoGet(ctx context.Context) (ImplResponse, error) {
	return Response(200, Info{
		Version: "1.0.0",
		Metadata: Metadata{
			TransactionId: "01H448Y0XEBQ73YG7WXXVFWSNX",
		},
	}), nil
}

// PoliciesGet - Get policies
func (s *DefaultApiService) PoliciesGet(ctx context.Context, clientId string, continuationToken string) (ImplResponse, error) {
	return Response(200, PoliciesGet200Response{
		Policies: []Policy{
			{
				Name:     "EXAMPLE_RULE_42",
				Version:  "1.0.0",
				Location: "s3://example-bucket/example_policy_42.json",
			},
			{
				Name:     "EXAMPLE_RULE_23",
				Version:  "1.0.0",
				Location: "s3://example-bucket/example_policy_23.json",
			},
			{
				Name:     "EXAMPLE_RULE_49",
				Version:  "1.0.0",
				Location: "s3://example-bucket/example_policy_49.json",
			},
			{
				Name:     "EXAMPLE_RULE_12",
				Version:  "1.0.0",
				Location: "s3://example-bucket/example_policy_12.json",
			},
			{
				Name:     "EXAMPLE_RULE_26",
				Version:  "1.0.0",
				Location: "s3://example-bucket/example_policy_26.json",
			},
			{
				Name:     "EXAMPLE_RULE_99",
				Version:  "1.0.0",
				Location: "s3://example-bucket/example_policy_99.json",
			},
		},
		Metadata: Metadata{
			TransactionId: "01H448Y0XEBQ73YG7WXXVFWSNX",
		},
	}), nil
}

// PoliciesPost - Add a policy
func (s *DefaultApiService) PoliciesPost(ctx context.Context, policiesPostRequest PoliciesPostRequest) (ImplResponse, error) {
	if rand.Intn(2) == 0 {
		return Response(201, Metadata{
			TransactionId: "01H44AMA9YXZ08JZCQZNV89TE8",
		}), nil
	}
	return Response(202, Metadata{
		TransactionId: "01H44AN4JEY1G1WNMXQ0D14QZ4",
	}), nil
}
