/*
 * Matter replacement sample PoC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConfigsGet200Response struct {

	// Configuration document
	Configuration map[string]interface{} `json:"configuration,omitempty"`

	Metadata Metadata `json:"metadata,omitempty"`
}

// AssertConfigsGet200ResponseRequired checks if the required fields are not zero-ed
func AssertConfigsGet200ResponseRequired(obj ConfigsGet200Response) error {
	if err := AssertMetadataRequired(obj.Metadata); err != nil {
		return err
	}
	return nil
}

// AssertRecurseConfigsGet200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ConfigsGet200Response (e.g. [][]ConfigsGet200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConfigsGet200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConfigsGet200Response, ok := obj.(ConfigsGet200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConfigsGet200ResponseRequired(aConfigsGet200Response)
	})
}
