/*
 * Matter replacement sample PoC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Metadata struct {

	TransactionId string `json:"transaction_id,omitempty"`
}

// AssertMetadataRequired checks if the required fields are not zero-ed
func AssertMetadataRequired(obj Metadata) error {
	return nil
}

// AssertRecurseMetadataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Metadata (e.g. [][]Metadata), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMetadataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMetadata, ok := obj.(Metadata)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMetadataRequired(aMetadata)
	})
}
