/*
 * Matter replacement sample PoC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Policy struct {

	Name string `json:"name,omitempty"`

	Version string `json:"version,omitempty"`

	Location string `json:"location,omitempty"`

	Metadata Metadata `json:"metadata,omitempty"`
}

// AssertPolicyRequired checks if the required fields are not zero-ed
func AssertPolicyRequired(obj Policy) error {
	if err := AssertMetadataRequired(obj.Metadata); err != nil {
		return err
	}
	return nil
}

// AssertRecursePolicyRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Policy (e.g. [][]Policy), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePolicyRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPolicy, ok := obj.(Policy)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPolicyRequired(aPolicy)
	})
}
