/*
 * Matter replacement sample PoC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Info struct {

	Version string `json:"version,omitempty"`

	Metadata Metadata `json:"metadata,omitempty"`
}

// AssertInfoRequired checks if the required fields are not zero-ed
func AssertInfoRequired(obj Info) error {
	if err := AssertMetadataRequired(obj.Metadata); err != nil {
		return err
	}
	return nil
}

// AssertRecurseInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Info (e.g. [][]Info), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInfo, ok := obj.(Info)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInfoRequired(aInfo)
	})
}
